Issue11 client profile page empty
OpenSRP/opensrp-client-fp pull request #27
Opened 2020-04-15 06:20 UTC by syedowaisali90

I have completed the UI setup.

2020-04-15 13:15 UTC, allan-allay commented
@syedowaisali90 Please resolve the merge conflicts above

2020-04-16 06:53 UTC, allan-on requested changes
The branch has conflicts that need to be resolved. Resolve the merge conflicts in this branch

2020-04-16 07:01 UTC, syedowaisali90 commented
Doing

2020-04-20 19:53 UTC, allan-on requested changes
Good work. ✅ 
- Left comments on sections where commented out code can be deleted. 
- Also, classes, tests, configs and other resources that won't be used in the app/project should be continually removed

2020-04-20 19:53 UTC, allan-on commented on opensrp-fp/src/main/java/org/smartregister/fp/common/provider/RegisterProvider.java
> +        }*/
Unused code is better off deleted

2020-04-20 19:53 UTC, allan-on commented on opensrp-fp/src/main/java/org/smartregister/fp/common/sync/BaseAncClientProcessorForJava.java
> +    /*
Delete if not in use

2020-04-20 19:53 UTC, allan-on commented on opensrp-fp/src/main/java/org/smartregister/fp/common/util/Utils.java
> +    public static void proceedToContact(String baseEntityId, HashMap<String, String> personObjectClient, Context context) {
If not in use the function can be deleted

2020-04-20 19:53 UTC, allan-on commented on opensrp-fp/src/main/java/org/smartregister/fp/common/util/Utils.java
> +    /*public static void finalizeForm(Activity context, HashMap<String, String> womanDetails, boolean isRefferal) {
This can also be deleted instead

2020-04-20 19:53 UTC, allan-on commented on opensrp-fp/src/main/java/org/smartregister/fp/features/home/model/RegisterFragmentModel.java
> +                + " on " + getRegisterQueryProvider().getDemographicTable() + "." + DBConstantsUtils.KeyUtils.BASE_ENTITY_ID + "= " + getRegisterQueryProvider().getDetailsTable() + "." + DBConstantsU
This can be deleted

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/java/org/smartregister/fp/features/home/repository/PatientRepository.java
> +                //detailsMap.put(DBConstantsUtils.KeyUtils.LAST_CONTACT_RECORD_DATE, cursor.getString(cursor.getColumnIndex(DBConstantsUtils.KeyUtils.LAST_CONTACT_RECORD_DATE)));
Deleting is better than commenting out

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/java/org/smartregister/fp/features/home/repository/PatientRepository.java
> +                    /*getRegisterQueryProvider().getDetailsTable() + "." + DBConstantsUtils.KeyUtils.YELLOW_FLAG_COUNT, getRegisterQueryProvider().getDetailsTable() + "." + DBConstantsUtils.KeyUtils.
Deleting is better than commenting out

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/java/org/smartregister/fp/features/home/repository/RegisterQueryProvider.java
> +                + " on " + getDemographicTable() + "." + DBConstantsUtils.KeyUtils.BASE_ENTITY_ID + "= " + getDetailsTable() + "." + DBConstantsUtils.KeyUtils.BASE_ENTITY_ID + " ");*/
Unused code can be removed

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/res/drawable/btn_start_visit_bg.xml
> +    <stroke android:width="1dp" android:color="#FFC9C9C9"/>
Colours and dimension values can be defined in the `res/` values for reuse

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/res/layout/no_health_data_record.xml
> +        android:textStyle="bold" />-->
This can be removed if not in use

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/res/layout/register_home_list_row.xml
> +                android:text="Patient Name, 18"
Is this a default value? Can be defined in `Strings.xml`?

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/res/layout/register_home_list_row.xml
> +                    android:text="GA: 12 weeks"
Is this a default value? Can be defined in `Strings.xml`?

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/res/layout/register_home_list_row.xml
> +                android:text="ID: 3034503"
Is this a default value? Can be defined in `Strings.xml`?

2020-04-20 19:53 UTC, allan-allay commented on opensrp-fp/src/main/res/layout/register_home_list_row.xml
> +                android:text="Levonorgestrel IUD (LNG-IUD)"
Is this a default value? Can be defined in `Strings.xml`?

2020-04-21 06:58 UTC, merged