Issue#64 - Bug fixing and enchantments
OpenSRP/opensrp-client-fp pull request #70
Opened 2020-06-15 07:50 UTC by zzainulabidin

Add adolescent calculation and counseling note #64 
Automated sync should be happening every 15 minutes #69 
Unable to view read-only FP visit in History tab #68 
Implement due only filter toggle on main register page #8 
Allow special characters #65

2020-06-22 08:20 UTC, dubdabasoduba requested changes

2020-06-22 08:20 UTC, dubdabasoduba commented on opensrp-fp/src/main/assets/json.form/fp_register.json
> +          "value": "[^0-9]*",
Is this regex correct

2020-06-24 07:55 UTC, zzainulabidin commented on opensrp-fp/src/main/assets/json.form/fp_register.json
> +          "value": "[^0-9]*",
Yes, we need to allow special characters too, so now we only restrict the numbers in the name.

2020-07-06 06:56 UTC, dubdabasoduba approved these changes

2020-07-06 06:59 UTC, merged